version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo running the Python code...
      - python Saeed-b2d2.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - Saeed-b2d2.py
